### ISSUE TITLE
hashivault_vars .... how would be works?

### ISSUE THREAD

**Issue by emper0r** [goethite/hashivault_vars#34]
Hi.. @easybe and @gbevan .. 
we found this repository with good project and we are trying to implement on our virtual environment

we are using right now ansible-5.2
installed hashivault_vars 0.2.0 without any errors using pip 
ansible 5.2 in this case use python 3.8

we recreate this path on vault for test

`/secret/ansible/groups/all`

inside a simple var for example:

`testvar = '123abc'`

```
vault kv get secret/ansible/groups/all
======= Metadata =======
Key                Value
---                -----
created_time       2022-02-15T14:55:53.343017959Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            1

===== Data =====
Key        Value
---        -----
testvar    123abc
```

and on playbook test can't found this var 

```
- name: Lookup hashicorp vault secrets
  hosts: localhost
  gather_facts: false
  connection: local
  vars:

  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ testvar }}"

```

output:

```
TASK [Debug test 3] *****************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'testvar' is undefined

```

**Comment by easybe** [comment]
Have you followed [these instructions](https://github.com/goethite/hashivault_vars#enable-in-ansible)? Alternatively, you can set the `ANSIBLE_VARS_PLUGINS` environment variable.

**Comment by emper0r** [comment]
Yes I did.
we got these on ansible.cfg

```
[defaults]
vars_plugins_enabled = host_group_vars,community.sops.sops,hashivault-vars
vars_plugins = /usr/local/bin/python_virtualenvs/ansible-5.2.0-devops_env10/lib/python3.8/site-packages/hashivault_vars

```

**Comment by easybe** [comment]
Did you try setting the environment variable `HASHIVAULT_VARS_DEBUG=1` in order to get some debug output?

**Comment by emper0r** [comment]
hi @easybe 
yes but still not get values from vault

vault server version `1.9.2`

![image](https://user-images.githubusercontent.com/819042/154219589-bc051c55-b8a1-41b2-85ee-584a731685af.png)

```
vault kv get secret/ansible/hosts/localhost
======= Metadata =======
Key                Value
---                -----
created_time       2022-02-16T07:44:24.514161357Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            1

===== Data =====
Key        Value
---        -----
testvar    123abc

```
```
HASHIVAULT_VARS> vault_addr:https://vault.domain.com
HASHIVAULT_VARS> TLS Verification:True
HASHIVAULT_VARS> Root Path:/secret/ansible
HASHIVAULT_VARS> get_vars **********************************
HASHIVAULT_VARS> lookup entities:[localhost]
HASHIVAULT_VARS> host vars:{'ansible_python_interpreter': '/usr/local/bin/python_virtualenvs/ansible-5.2.0-devops_env10/bin/python', 'ansible_connection': 'local'}
HASHIVAULT_VARS> host groups:[]
HASHIVAULT_VARS> _read_vault (cached) hosts/localhost: {}
HASHIVAULT_VARS> _read_vault (cached) local/hosts/localhost: {}
HASHIVAULT_VARS> get_vars: {'ansible_python_interpreter': '/usr/local/bin/python_virtualenvs/ansible-5.2.0-devops_env10/bin/python', 'ansible_connection': 'local'}
HASHIVAULT_VARS> in __init__
HASHIVAULT_VARS> vault_addr:https://vault.domain.com
HASHIVAULT_VARS> TLS Verification:True
HASHIVAULT_VARS> Root Path:/secret/ansible
HASHIVAULT_VARS> get_vars **********************************
HASHIVAULT_VARS> lookup entities:[localhost]
HASHIVAULT_VARS> host vars:{'ansible_python_interpreter': '/usr/local/bin/python_virtualenvs/ansible-5.2.0-devops_env10/bin/python', 'ansible_connection': 'local'}
HASHIVAULT_VARS> host groups:[]
HASHIVAULT_VARS> _read_vault (cached) hosts/localhost: {}
HASHIVAULT_VARS> _read_vault (cached) local/hosts/localhost: {}
HASHIVAULT_VARS> get_vars: {'ansible_python_interpreter': '/usr/local/bin/python_virtualenvs/ansible-5.2.0-devops_env10/bin/python', 'ansible_connection': 'local'}

TASK [Debug test] **********************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'testvar' is undefined

```

test.yml
```
- name: Lookup hashicorp vault secrets
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"
    vault_url: "{{ lookup('env', 'VAULT_ADDR') }}"

  tasks:
    - name: Debug test
      ansible.builtin.debug:
        msg: "{{ testvar }}"
```
